#!/usr/bin/env python3
"""Generate GCS config files for simulation or hardware deployment.

Outputs:
- config/zenoh/gcs_bridge.generated.json5
- config/tmuxinator/gcs.generated.yml
- config/rviz/flight_visualization.generated.rviz
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List


def parse_env_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if len(value) >= 2 and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'")):
            value = value[1:-1]
        values[key] = value
    return values


def build_gcs_bridge_text(
    mode: str,
    num_uavs: int,
    uav_ips: List[str],
    zenoh_port: int,
) -> str:
    if mode == "sim":
        endpoints = "\n".join([f'      "tcp/localhost:{7447 + i}",' for i in range(num_uavs)])
    else:
        endpoints = "\n".join([f'      "tcp/{ip}:7447",' for ip in uav_ips])

    topic_allowlist = """          "/uav.*/uav_state",
          "/uav.*/estimated_state",
          "/uav.*/trajectory_setpoint",
          "/uav.*/safety_status",
          "/uav.*/estimation_status",
          "/uav.*/control_status",
          "/uav.*/trajectory_status",
          "/uav.*/status",
          "/uav.*/gps_status",
          "/tf",
          "/tf_static","""

    return f"""// AUTO-GENERATED by docker/scripts/generate_gcs_config.py. DO NOT EDIT.
// Regenerate with: make generate-gcs
{{
  mode: "peer",

  listen: {{
    endpoints: ["tcp/0.0.0.0:{zenoh_port}"],
  }},

  connect: {{
    endpoints: [
{endpoints}
    ],
  }},

  plugins: {{
    ros2dds: {{
      domain: 99,

      allow: {{
        publishers: [],
        subscribers: [
{topic_allowlist}
        ],
        service_servers: [],
        service_clients: [
          "/uav.*/arm",
          "/uav.*/uav_manager/clear_emergency",
        ],
        action_servers: [],
        action_clients: [
          "/uav.*/uav_manager/takeoff",
          "/uav.*/uav_manager/land",
          "/uav.*/execute_tree",
        ],
      }},
    }},
  }},
}}
"""


def build_tmux_text(drone_ids: List[int]) -> str:
    pane_lines = "\n".join(
        [
            f"        - uav{did}_tui: ros2 run tui_status tui_status_node --ros-args -p uav_namespace:=/uav{did}"
            for did in drone_ids
        ]
    )

    return f"""# AUTO-GENERATED by docker/scripts/generate_gcs_config.py. DO NOT EDIT.
# Regenerate with: make generate-gcs
name: gcs
root: <%= ENV.fetch("ROS_WS", "/ros2_ws") %>

pre_window:
  - source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash
  - '[ -f install/setup.bash ] && source install/setup.bash || true'
  - export ROS_DOMAIN_ID=99
  - clear

windows:
  - ground_station:
      layout: tiled
      panes:
{pane_lines}
  - rviz:
      panes:
        - rviz_multi: ros2 launch rviz_plugins multi_flight_visualization.launch.py num_uavs:={len(drone_ids)} uav_namespace_prefix:=uav drone_ids:={','.join(str(d) for d in drone_ids)} rviz_config:=${{ROS_WS:-/ros2_ws}}/docker/config/rviz/flight_visualization.generated.rviz
  - topics:
      panes:
        - ros2 topic list
"""


def build_generated_rviz_text(drone_ids: List[int], template_text: str) -> str:
    frame_entries = ["        base_link_frd:\n          Value: false"]
    frame_entries.extend(
        [f"        uav{did}/base_link_frd:\n          Value: false" for did in drone_ids]
    )
    frames_block = "      Frames:\n        All Enabled: true\n" + "\n".join(frame_entries) + "\n"

    marker_scale_token = "      Marker Scale:"
    marker_idx = template_text.find(marker_scale_token)
    if marker_idx == -1:
        raise ValueError("Could not find 'Marker Scale:' in RViz template.")

    frames_token = "      Frames:\n"
    frames_idx = template_text.find(frames_token)
    if frames_idx != -1 and frames_idx < marker_idx:
        rviz_text = template_text[:frames_idx] + frames_block + template_text[marker_idx:]
    else:
        rviz_text = template_text[:marker_idx] + frames_block + template_text[marker_idx:]

    return rviz_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate GCS config files for sim or hardware.")
    parser.add_argument(
        "--mode",
        choices=["sim", "hardware"],
        default=None,
        help="Deployment mode (default: from GCS_MODE in .env).",
    )
    parser.add_argument("--num-uavs", type=int, default=None, help="Override NUM_UAVS from .env.")
    parser.add_argument(
        "--uav-ips",
        type=str,
        default=None,
        help="Comma-separated UAV IPs (required for hardware mode).",
    )
    parser.add_argument(
        "--zenoh-port",
        type=int,
        default=None,
        help="GCS Zenoh listen port (default: from GCS_ZENOH_PORT in .env, or 7459).",
    )
    parser.add_argument(
        "--drone-ids",
        type=str,
        default=None,
        help="Comma-separated DRONE_IDs (e.g. 2,4). Defaults to 1..N for sim.",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Path to .env file (defaults to docker/.env).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    docker_dir = Path(__file__).resolve().parents[1]

    env_file = args.env_file if args.env_file is not None else (docker_dir / ".env")
    env_values = parse_env_file(env_file)

    # Also load .env.local overrides
    env_local = env_file.parent / ".env.local"
    env_local_values = parse_env_file(env_local)
    env_values.update(env_local_values)

    mode = args.mode or env_values.get("GCS_MODE", "sim")
    num_uavs = args.num_uavs
    if num_uavs is None:
        num_uavs = int(env_values.get("GCS_NUM_UAVS", env_values.get("NUM_UAVS", "2")))
    zenoh_port = args.zenoh_port or int(env_values.get("GCS_ZENOH_PORT", "7459"))

    if num_uavs < 1:
        raise ValueError("NUM_UAVS must be >= 1")

    uav_ips: List[str] = []
    if mode == "hardware":
        ip_str = args.uav_ips or env_values.get("GCS_UAV_IPS", "")
        if not ip_str:
            raise ValueError("Hardware mode requires --uav-ips or GCS_UAV_IPS in .env/.env.local")
        uav_ips = [ip.strip() for ip in ip_str.split(",") if ip.strip()]
        num_uavs = len(uav_ips)

    drone_id_str = args.drone_ids or env_values.get("GCS_DRONE_IDS", "")
    if drone_id_str:
        drone_ids = [int(d.strip()) for d in drone_id_str.split(",") if d.strip()]
    else:
        drone_ids = list(range(1, num_uavs + 1))

    gcs_bridge_path = docker_dir / "config" / "zenoh" / "gcs_bridge.generated.json5"
    tmux_path = docker_dir / "config" / "tmuxinator" / "gcs.generated.yml"
    rviz_template_path = (
        docker_dir.parent
        / "src"
        / "peregrine_core"
        / "rviz_plugins"
        / "rviz"
        / "flight_visualization.rviz"
    )
    generated_rviz_path = docker_dir / "config" / "rviz" / "flight_visualization.generated.rviz"

    gcs_bridge_path.parent.mkdir(parents=True, exist_ok=True)
    gcs_bridge_path.write_text(
        build_gcs_bridge_text(mode, num_uavs, uav_ips, zenoh_port), encoding="utf-8"
    )

    tmux_path.parent.mkdir(parents=True, exist_ok=True)
    tmux_path.write_text(build_tmux_text(drone_ids), encoding="utf-8")

    generated_rviz_path.parent.mkdir(parents=True, exist_ok=True)
    if rviz_template_path.exists():
        generated_rviz_path.write_text(
            build_generated_rviz_text(drone_ids, rviz_template_path.read_text(encoding="utf-8")),
            encoding="utf-8",
        )
        print(f" - {generated_rviz_path}")
    else:
        print(f" ! RViz template not found at {rviz_template_path}, skipping RViz config generation")

    print(f"Generated GCS configs for mode={mode}, num_uavs={num_uavs}")
    print(f" - {gcs_bridge_path}")
    print(f" - {tmux_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
