#!/usr/bin/env python3
"""Generate GCS config files for simulation or hardware deployment.

Outputs:
- config/zenoh/gcs_bridge.generated.json5
- config/tmuxinator/gcs.generated.yml
- config/rviz/flight_visualization.generated.rviz
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List


def parse_env_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if len(value) >= 2 and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'")):
            value = value[1:-1]
        values[key] = value
    return values


def build_gcs_bridge_text(
    mode: str,
    num_uavs: int,
    uav_ips: List[str],
    zenoh_port: int,
) -> str:
    if mode == "sim":
        endpoints = "\n".join([f'      "tcp/localhost:{7447 + i}",' for i in range(num_uavs)])
    else:
        endpoints = "\n".join([f'      "tcp/{ip}:7447",' for ip in uav_ips])

    topic_allowlist = """          "/uav.*/uav_state",
          "/uav.*/estimated_state",
          "/uav.*/trajectory_setpoint",
          "/uav.*/safety_status",
          "/uav.*/estimation_status",
          "/uav.*/control_status",
          "/uav.*/trajectory_status",
          "/uav.*/status",
          "/uav.*/gps_status",
          "/uav.*/compute_status",
          "/uav.*/viz/coverage_grid",
          "/uav.*/viz/planned_path",
          "/uav.*/viz/coverage_swath",
          "/fleet/agent_state",
          "/tf",
          "/tf_static","""

    return f"""// AUTO-GENERATED by docker/scripts/generate_gcs_config.py. DO NOT EDIT.
// Regenerate with: make generate-gcs
{{
  mode: "peer",

  listen: {{
    endpoints: ["tcp/0.0.0.0:{zenoh_port}"],
  }},

  connect: {{
    endpoints: [
{endpoints}
    ],
  }},

  plugins: {{
    ros2dds: {{
      domain: 99,

      // Long-running BT missions (e.g. the surveillance sweep ~6 min) keep the
      // ExecuteTree action's get_result query pending past the 300s plugin
      // default, which made the GCS client report FAILED even though the
      // mission flew + landed. Raise the action result timeout above the
      // longest mission (must match the UAV bridge; see uav_bridge.json5).
      queries_timeout: {{
        actions: {{
          get_result: 3600.0,
        }},
      }},

      allow: {{
        publishers: [],
        subscribers: [
{topic_allowlist}
        ],
        service_servers: [],
        service_clients: [
          "/uav.*/arm",
          "/uav.*/uav_manager/clear_emergency",
        ],
        action_servers: [],
        action_clients: [
          "/uav.*/uav_manager/takeoff",
          "/uav.*/uav_manager/land",
          "/uav.*/execute_tree",
        ],
      }},
    }},
  }},
}}
"""


def build_tmux_text(drone_ids: List[int]) -> str:
    pane_lines = "\n".join(
        [
            f"        - uav{did}_tui: ros2 run tui_status tui_status_node --ros-args -p uav_namespace:=/uav{did}"
            for did in drone_ids
        ]
    )

    return f"""# AUTO-GENERATED by docker/scripts/generate_gcs_config.py. DO NOT EDIT.
# Regenerate with: make generate-gcs
name: gcs
root: <%= ENV.fetch("ROS_WS", "/ros2_ws") %>

pre_window:
  - source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash
  - '[ -f install/setup.bash ] && source install/setup.bash || true'
  - export ROS_DOMAIN_ID=99
  - clear

windows:
  - ground_station:
      layout: tiled
      panes:
{pane_lines}
  - commands:
      panes:
        - mission_shell: echo "Ready. Usage -- python3 -m peregrine_client.missions.trigger_trajectory [--uavs uav1,uav2] [--tree MultiTrajectory]"
  - rviz:
      panes:
        - rviz_multi: ros2 launch rviz_plugins multi_flight_visualization.launch.py num_uavs:={len(drone_ids)} uav_namespace_prefix:=uav drone_ids:={','.join(str(d) for d in drone_ids)} rviz_config:=${{ROS_WS:-/ros2_ws}}/docker/config/rviz/flight_visualization.generated.rviz
  - topics:
      panes:
        - ros2 topic list
"""


# ── Per-UAV color: must match the C++ Turbo colormap so RViz Path colors equal the
# marker colors emitted by trajectory_manager / flight_visualizer. Mirror of
# frame_transforms/viz_colormap.hpp (turbo + golden-ratio index spread). N-agnostic.
_GOLDEN_RATIO_CONJUGATE = 0.618033988749894848


def _turbo(x: float) -> tuple[float, float, float]:
    x = max(0.0, min(1.0, x))
    x2 = x * x
    x3 = x2 * x
    x4 = x2 * x2
    x5 = x4 * x
    r = 0.13572138 + 4.61539260 * x - 42.66032258 * x2 + 132.13108234 * x3 - 152.94239396 * x4 + 59.28637943 * x5
    g = 0.09140261 + 2.19418839 * x + 4.84296658 * x2 - 14.18503333 * x3 + 4.27729857 * x4 + 2.82956604 * x5
    b = 0.10667330 + 12.64194608 * x - 60.58204836 * x2 + 110.36276771 * x3 - 89.90310912 * x4 + 27.34824973 * x5
    return (max(0.0, min(1.0, r)), max(0.0, min(1.0, g)), max(0.0, min(1.0, b)))


def _uav_rgb255(uav_id: int) -> tuple[int, int, int]:
    frac = (uav_id * _GOLDEN_RATIO_CONJUGATE) % 1.0
    r, g, b = _turbo(frac)
    return (round(r * 255), round(g * 255), round(b * 255))


def _grid_display() -> str:
    return """    - Alpha: 0.35
      Cell Size: 1
      Class: rviz_default_plugins/Grid
      Color: 180; 180; 185
      Enabled: true
      Line Style:
        Line Width: 0.03
        Value: Lines
      Name: Grid
      Plane: XY
      Plane Cell Count: 30
      Reference Frame: <Fixed Frame>
      Value: true
"""


def _tf_display(drone_ids: List[int]) -> str:
    entries = ["        base_link_frd:\n          Value: false"]
    entries.extend(
        [f"        uav{did}/base_link_frd:\n          Value: false" for did in drone_ids]
    )
    frames = "        All Enabled: true\n" + "\n".join(entries)
    return f"""    - Class: rviz_default_plugins/TF
      Enabled: true
      Frame Timeout: 15
      Frames:
{frames}
      Marker Scale: 5
      Name: TF
      Show Arrows: true
      Show Axes: true
      Show Names: true
      Tree:
        {{}}
      Update Interval: 0
      Value: true
"""


def _path_display(name: str, topic: str, rgb: tuple[int, int, int], alpha: float, latched: bool) -> str:
    r, g, b = rgb
    dur = "Transient Local" if latched else "Volatile"
    return f"""    - Alpha: {alpha}
      Buffer Length: 1
      Class: rviz_default_plugins/Path
      Color: {r}; {g}; {b}
      Enabled: true
      Head Diameter: 0.1
      Head Length: 0.1
      Length: 0.1
      Line Style: Lines
      Line Width: 0.04
      Name: {name}
      Offset:
        X: 0
        Y: 0
        Z: 0
      Pose Color: 255; 85; 85
      Pose Style: None
      Radius: 0.03
      Shaft Diameter: 0.03
      Shaft Length: 0.1
      Topic:
        Depth: 5
        Durability Policy: {dur}
        Filter size: 10
        History Policy: Keep Last
        Reliability Policy: Reliable
        Value: {topic}
      Value: true
"""


def _marker_array_display(name: str, topic: str, latched: bool, depth: int = 20) -> str:
    dur = "Transient Local" if latched else "Volatile"
    return f"""    - Class: rviz_default_plugins/MarkerArray
      Enabled: true
      Name: {name}
      Namespaces:
        {{}}
      Topic:
        Depth: {depth}
        Durability Policy: {dur}
        History Policy: Keep Last
        Reliability Policy: Reliable
        Value: {topic}
      Value: true
"""


def _build_displays_block(drone_ids: List[int]) -> str:
    block = _grid_display() + _tf_display(drone_ids)
    for did in drone_ids:
        rgb = _uav_rgb255(did)
        block += _marker_array_display(f"uav{did} Markers", f"/uav{did}/viz/markers", latched=False)
        block += _marker_array_display(
            f"uav{did} Coverage Grid", f"/uav{did}/viz/coverage_grid", latched=True
        )
        block += _marker_array_display(
            f"uav{did} Coverage Swath", f"/uav{did}/viz/coverage_swath", latched=True
        )
        # Reference plan = straight waypoints, low opacity; Actual = flown trail, full opacity.
        block += _path_display(
            f"uav{did} Planned Path", f"/uav{did}/viz/planned_path", rgb, alpha=0.4, latched=True
        )
        block += _path_display(
            f"uav{did} Actual Path", f"/uav{did}/viz/actual_path", rgb, alpha=1.0, latched=False
        )
    block += _marker_array_display("Fleet Separation", "/fleet/viz/separation", latched=False)
    return block


def build_generated_rviz_text(drone_ids: List[int], template_text: str) -> str:
    """Rebuild the Displays list for N UAVs (per-UAV colors, grid/path/swath/separation).

    Keeps the template's Panels / Global Options / Tools / Views / Window Geometry verbatim
    and replaces only the Displays sequence, then pins the fixed frame to 'world'.
    """
    displays_token = "  Displays:\n"
    enabled_token = "\n  Enabled: true\n"
    di = template_text.find(displays_token)
    ei = template_text.find(enabled_token)
    if di == -1 or ei == -1 or ei < di:
        raise ValueError("RViz template missing Displays/Enabled anchors.")

    head = template_text[: di + len(displays_token)]
    tail = template_text[ei + 1:]  # from "  Enabled: true\n" onward
    rviz_text = head + _build_displays_block(drone_ids) + tail
    return rviz_text.replace("Fixed Frame: map", "Fixed Frame: world")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate GCS config files for sim or hardware.")
    parser.add_argument(
        "--mode",
        choices=["sim", "hardware"],
        default=None,
        help="Deployment mode (default: from GCS_MODE in .env).",
    )
    parser.add_argument("--num-uavs", type=int, default=None, help="Override NUM_UAVS from .env.")
    parser.add_argument(
        "--uav-ips",
        type=str,
        default=None,
        help="Comma-separated UAV IPs (required for hardware mode).",
    )
    parser.add_argument(
        "--zenoh-port",
        type=int,
        default=None,
        help="GCS Zenoh listen port (default: from GCS_ZENOH_PORT in .env, or 7459).",
    )
    parser.add_argument(
        "--drone-ids",
        type=str,
        default=None,
        help="Comma-separated DRONE_IDs (e.g. 2,4). Defaults to 1..N for sim.",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Path to .env file (defaults to docker/.env).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    docker_dir = Path(__file__).resolve().parents[1]

    env_file = args.env_file if args.env_file is not None else (docker_dir / ".env")
    env_values = parse_env_file(env_file)

    # Also load .env.local overrides
    env_local = env_file.parent / ".env.local"
    env_local_values = parse_env_file(env_local)
    env_values.update(env_local_values)

    mode = args.mode or env_values.get("GCS_MODE", "sim")
    num_uavs = args.num_uavs
    if num_uavs is None:
        num_uavs = int(env_values.get("GCS_NUM_UAVS", env_values.get("NUM_UAVS", "2")))
    zenoh_port = args.zenoh_port or int(env_values.get("GCS_ZENOH_PORT", "7459"))

    if num_uavs < 1:
        raise ValueError("NUM_UAVS must be >= 1")

    uav_ips: List[str] = []
    if mode == "hardware":
        ip_str = args.uav_ips or env_values.get("GCS_UAV_IPS", "")
        if not ip_str:
            raise ValueError("Hardware mode requires --uav-ips or GCS_UAV_IPS in .env/.env.local")
        uav_ips = [ip.strip() for ip in ip_str.split(",") if ip.strip()]
        num_uavs = len(uav_ips)

    drone_id_str = args.drone_ids or env_values.get("GCS_DRONE_IDS", "")
    if drone_id_str:
        drone_ids = [int(d.strip()) for d in drone_id_str.split(",") if d.strip()]
    else:
        drone_ids = list(range(1, num_uavs + 1))

    gcs_bridge_path = docker_dir / "config" / "zenoh" / "gcs_bridge.generated.json5"
    tmux_path = docker_dir / "config" / "tmuxinator" / "gcs.generated.yml"
    rviz_template_path = (
        docker_dir.parent
        / "src"
        / "peregrine_core"
        / "rviz_plugins"
        / "rviz"
        / "flight_visualization.rviz"
    )
    generated_rviz_path = docker_dir / "config" / "rviz" / "flight_visualization.generated.rviz"

    gcs_bridge_path.parent.mkdir(parents=True, exist_ok=True)
    gcs_bridge_path.write_text(
        build_gcs_bridge_text(mode, num_uavs, uav_ips, zenoh_port), encoding="utf-8"
    )

    tmux_path.parent.mkdir(parents=True, exist_ok=True)
    tmux_path.write_text(build_tmux_text(drone_ids), encoding="utf-8")

    generated_rviz_path.parent.mkdir(parents=True, exist_ok=True)
    if rviz_template_path.exists():
        generated_rviz_path.write_text(
            build_generated_rviz_text(drone_ids, rviz_template_path.read_text(encoding="utf-8")),
            encoding="utf-8",
        )
        print(f" - {generated_rviz_path}")
    else:
        print(f" ! RViz template not found at {rviz_template_path}, skipping RViz config generation")

    print(f"Generated GCS configs for mode={mode}, num_uavs={num_uavs}")
    print(f" - {gcs_bridge_path}")
    print(f" - {tmux_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
