#!/usr/bin/env python3
"""Generate multi-UAV SITL docker config files from NUM_UAVS.

Outputs:
- compose/docker-compose.multi-sitl.yml
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict


def parse_env_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if len(value) >= 2 and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'")):
            value = value[1:-1]
        values[key] = value
    return values


def build_uav_service(service_idx: int) -> str:
    i = service_idx
    drone_id = i + 1
    ros_domain_id = drone_id
    zenoh_port = 7447 + i
    microxrce_port = 8888 + 2 * i
    px4_namespace = "" if i == 0 else f"/px4_{i}"
    target_system_id = drone_id
    service_name = f"uav{drone_id}"
    uav_namespace = f"/uav{drone_id}"

    px4_ns_arg = f" px4_namespace:={px4_namespace}" if px4_namespace else ""

    return f"""  # -- UAV {drone_id}: Peregrine stack + Zenoh bridge --------------------------------
  {service_name}:
    <<: *common
    container_name: ${{PROJECT_NAME:-ros2-px4-flight}}-{service_name}
    environment:
      - DISPLAY=${{DISPLAY:-:0}}
      - DRONE_ID={drone_id}
      - ROS_LOCALHOST_ONLY=1
      - ROS_WS=${{ROS_WS:-/ros2_ws}}
      - ZENOH_BRIDGE_CONFIG=${{ROS_WS:-/ros2_ws}}/docker/config/zenoh/uav_bridge.json5
      - ZENOH_PORT={zenoh_port}
    depends_on:
      sim:
        condition: service_started
    command: >
      bash -lc "
        echo '[{service_name}] Waiting for MicroXRCEAgent UDP port {microxrce_port}...' &&
        timeout 90 bash -c 'until ss -lnup | grep -q \\\":{microxrce_port} \\\"; do sleep 1; done' &&
        sleep 2 &&
        source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash &&
        [ -f ${{ROS_WS:-/ros2_ws}}/install/setup.bash ] && source ${{ROS_WS:-/ros2_ws}}/install/setup.bash;
        ros2 launch peregrine_bringup single_uav.launch.py start_microxrce_agent:=false ros_domain_id:={ros_domain_id} microxrce_port:={microxrce_port} uav_namespace:={uav_namespace}{px4_ns_arg} target_system_id:={target_system_id} use_sim_time:=true
      "
"""


def build_compose_text(num_uavs: int) -> str:
    uav_services = "".join(build_uav_service(i) for i in range(num_uavs))

    return f"""# AUTO-GENERATED by docker/scripts/generate_multi_sitl.py. DO NOT EDIT.
# Regenerate with: make generate-multi

x-common: &common
  image: ${{PROJECT_NAME:-ros2-px4-flight}}-simulation:latest
  network_mode: host
  ipc: host
  privileged: true
  stdin_open: true
  tty: true
  volumes:
    - ../../:${{ROS_WS:-/ros2_ws}}:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ${{HOME}}/.Xauthority:/home/${{CONTAINER_USER:-peregrine}}/.Xauthority:ro

services:
  # -- Shared Gazebo + PX4 SITL instances --------------------------------------
  sim:
    <<: *common
    container_name: ${{PROJECT_NAME:-ros2-px4-flight}}-multi-sim
    environment:
      - DISPLAY=${{DISPLAY:-:0}}
      - ROS_LOCALHOST_ONLY=1
      - ROS_WS=${{ROS_WS:-/ros2_ws}}
      - PX4_GZ_WORLD=${{PX4_GZ_WORLD:-default}}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphics]
    command: >
      bash -lc "
        source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash &&
        [ -f ${{ROS_WS:-/ros2_ws}}/install/setup.bash ] && source ${{ROS_WS:-/ros2_ws}}/install/setup.bash;
        ros2 launch peregrine_bringup multi_uav_sitl.launch.py num_uavs:={num_uavs} px4_gz_world:=${{PX4_GZ_WORLD:-default}} uav_spawn_spacing_m:=${{UAV_SPAWN_SPACING_M:-5.0}} px4_base_delay:=${{PX4_BASE_DELAY:-8.0}} px4_stagger_delay:=${{PX4_STAGGER_DELAY:-5.0}} headless:=0
      "

{uav_services}"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate multi-UAV SITL docker config files.")
    parser.add_argument("--num-uavs", type=int, default=None, help="Override NUM_UAVS from .env.")
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Path to .env file (defaults to docker/.env).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    docker_dir = Path(__file__).resolve().parents[1]

    env_file = args.env_file if args.env_file is not None else (docker_dir / ".env")
    env_values = parse_env_file(env_file)

    num_uavs = args.num_uavs
    if num_uavs is None:
        num_uavs = int(env_values.get("NUM_UAVS", "2"))

    if num_uavs < 1:
        raise ValueError("NUM_UAVS must be >= 1")

    compose_path = docker_dir / "compose" / "docker-compose.multi-sitl.yml"

    compose_path.write_text(build_compose_text(num_uavs), encoding="utf-8")

    print(f"Generated configs for NUM_UAVS={num_uavs}")
    print(f" - {compose_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
