#!/usr/bin/env python3
"""Generate multi-UAV SITL docker config files from NUM_UAVS.

Outputs:
- compose/docker-compose.multi-sitl.yml
- config/zenoh/gcs_bridge.json5
- config/tmuxinator/gcs.yml
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List


def parse_env_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if len(value) >= 2 and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'")):
            value = value[1:-1]
        values[key] = value
    return values


def build_uav_service(service_idx: int) -> str:
    i = service_idx
    drone_id = i + 1
    ros_domain_id = drone_id
    zenoh_port = 7447 + i
    microxrce_port = 8888 + 2 * i
    px4_namespace = "" if i == 0 else f"/px4_{i}"
    target_system_id = drone_id
    service_name = f"uav{drone_id}"
    uav_namespace = f"/uav{drone_id}"
    base_link_frame = f"uav{drone_id}/base_link"
    base_link_frd_frame = f"uav{drone_id}/base_link_frd"

    px4_ns_arg = f" px4_namespace:={px4_namespace}" if px4_namespace else ""

    return f"""  # -- UAV {drone_id}: Peregrine stack + Zenoh bridge --------------------------------
  {service_name}:
    <<: *common
    container_name: ${{PROJECT_NAME:-ros2-px4-flight}}-{service_name}
    environment:
      - DISPLAY=${{DISPLAY:-:0}}
      - DRONE_ID={drone_id}
      - ROS_LOCALHOST_ONLY=1
      - ROS_WS=${{ROS_WS:-/ros2_ws}}
      - ZENOH_BRIDGE_CONFIG=${{ROS_WS:-/ros2_ws}}/docker/config/zenoh/uav_bridge.json5
      - ZENOH_PORT={zenoh_port}
    depends_on:
      sim:
        condition: service_started
    command: >
      bash -lc "
        echo '[{service_name}] Waiting for MicroXRCEAgent UDP port {microxrce_port}...' &&
        timeout 90 bash -c 'until ss -lnup | grep -q \\\":{microxrce_port} \\\"; do sleep 1; done' &&
        sleep 2 &&
        source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash &&
        [ -f ${{ROS_WS:-/ros2_ws}}/install/setup.bash ] && source ${{ROS_WS:-/ros2_ws}}/install/setup.bash;
        ros2 launch peregrine_bringup single_uav.launch.py start_microxrce_agent:=false ros_domain_id:={ros_domain_id} microxrce_port:={microxrce_port} uav_namespace:={uav_namespace}{px4_ns_arg} target_system_id:={target_system_id} odom_frame:=odom base_link_frame:={base_link_frame} base_link_frd_frame:={base_link_frd_frame} use_sim_time:=true
      "
"""


def build_compose_text(num_uavs: int) -> str:
    uav_services = "".join(build_uav_service(i) for i in range(num_uavs))
    gcs_zenoh_port = 7447 + num_uavs

    depends = "\n".join(
        [
            f"      uav{i + 1}:\n        condition: service_started"
            for i in range(num_uavs)
        ]
    )

    poll_checks = " && ".join(
        [
            f'until ss -lntp | grep -q \\":{7447 + i} \\"; do sleep 1; done'
            for i in range(num_uavs)
        ]
    )

    return f"""# AUTO-GENERATED by docker/scripts/generate_multi_sitl.py. DO NOT EDIT.
# Regenerate with: make generate-multi

x-common: &common
  image: ${{PROJECT_NAME:-ros2-px4-flight}}-simulation:latest
  network_mode: host
  ipc: host
  privileged: true
  stdin_open: true
  tty: true
  volumes:
    - ../../:${{ROS_WS:-/ros2_ws}}:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ${{HOME}}/.Xauthority:/home/${{CONTAINER_USER:-peregrine}}/.Xauthority:ro

services:
  # -- Shared Gazebo + PX4 SITL instances --------------------------------------
  sim:
    <<: *common
    container_name: ${{PROJECT_NAME:-ros2-px4-flight}}-multi-sim
    environment:
      - DISPLAY=${{DISPLAY:-:0}}
      - ROS_LOCALHOST_ONLY=1
      - ROS_WS=${{ROS_WS:-/ros2_ws}}
      - PX4_GZ_WORLD=${{PX4_GZ_WORLD:-default}}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphics]
    command: >
      bash -lc "
        source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash &&
        [ -f ${{ROS_WS:-/ros2_ws}}/install/setup.bash ] && source ${{ROS_WS:-/ros2_ws}}/install/setup.bash;
        ros2 launch peregrine_bringup multi_uav_sitl.launch.py num_uavs:={num_uavs} px4_gz_world:=${{PX4_GZ_WORLD:-default}} uav_spawn_spacing_m:=${{UAV_SPAWN_SPACING_M:-5.0}} px4_base_delay:=${{PX4_BASE_DELAY:-8.0}} px4_stagger_delay:=${{PX4_STAGGER_DELAY:-5.0}} headless:=0
      "

{uav_services}  # -- GCS: Ground station TUI + Zenoh bridge -------------------------------------
  gcs:
    <<: *common
    container_name: ${{PROJECT_NAME:-ros2-px4-flight}}-gcs
    environment:
      - DISPLAY=${{DISPLAY:-:0}}
      - DRONE_ID=99
      - ROS_LOCALHOST_ONLY=1
      - ROS_WS=${{ROS_WS:-/ros2_ws}}
      - ZENOH_BRIDGE_CONFIG=${{ROS_WS:-/ros2_ws}}/docker/config/zenoh/gcs_bridge.json5
      - ZENOH_PORT={gcs_zenoh_port}
    depends_on:
{depends}
    command: >
      bash -lc "
        echo '[gcs] Waiting for UAV Zenoh peers...' &&
        timeout 120 bash -c '{poll_checks}' &&
        sleep 2 &&
        source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash &&
        [ -f ${{ROS_WS:-/ros2_ws}}/install/setup.bash ] && source ${{ROS_WS:-/ros2_ws}}/install/setup.bash;
        export ROS_DOMAIN_ID=99;
        tmuxinator start -p ${{ROS_WS:-/ros2_ws}}/docker/config/tmuxinator/gcs.yml
      "
"""


def build_gcs_bridge_text(num_uavs: int) -> str:
    endpoints = "\n".join([f'      "tcp/localhost:{7447 + i}",' for i in range(num_uavs)])
    return f"""// AUTO-GENERATED by docker/scripts/generate_multi_sitl.py. DO NOT EDIT.
// Regenerate with: make generate-multi
{{
  mode: "peer",

  listen: {{
    endpoints: ["tcp/0.0.0.0:{7447 + num_uavs}"],
  }},

  connect: {{
    endpoints: [
{endpoints}
    ],
  }},

  plugins: {{
    ros2dds: {{
      domain: 99,

      allow: {{
        publishers: [],
        subscribers: [
          "/uav.*/uav_state",
          "/uav.*/estimated_state",
          "/uav.*/trajectory_setpoint",
          "/uav.*/safety_status",
          "/uav.*/estimation_status",
          "/uav.*/control_status",
          "/uav.*/trajectory_status",
          "/uav.*/status",
          "/uav.*/gps_status",
          "/tf",
          "/tf_static",
        ],
        service_servers: [],
        service_clients: [],
        action_servers: [],
        action_clients: [],
      }},
    }},
  }},
}}
"""


def build_tmux_text(num_uavs: int) -> str:
    layout = "tiled"
    pane_lines = "\n".join(
        [
            f"        - uav{i + 1}_tui: ros2 run tui_status tui_status_node --ros-args -p uav_namespace:=/uav{i + 1}"
            for i in range(num_uavs)
        ]
    )

    return f"""# AUTO-GENERATED by docker/scripts/generate_multi_sitl.py. DO NOT EDIT.
# Regenerate with: make generate-multi
name: gcs
root: <%= ENV.fetch("ROS_WS", "/ros2_ws") %>

pre_window:
  - source /opt/ros/${{ROS_DISTRO:-humble}}/setup.bash
  - '[ -f install/setup.bash ] && source install/setup.bash || true'
  - export ROS_DOMAIN_ID=99
  - clear

windows:
  - ground_station:
      layout: {layout}
      panes:
{pane_lines}
  - rviz:
      panes:
        - rviz_uav1: ros2 launch rviz_plugins flight_visualization.launch.py uav_namespace:=/uav1
  - topics:
      panes:
        - ros2 topic list
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate multi-UAV SITL docker config files.")
    parser.add_argument("--num-uavs", type=int, default=None, help="Override NUM_UAVS from .env.")
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Path to .env file (defaults to docker/.env).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    docker_dir = Path(__file__).resolve().parents[1]

    env_file = args.env_file if args.env_file is not None else (docker_dir / ".env")
    env_values = parse_env_file(env_file)

    num_uavs = args.num_uavs
    if num_uavs is None:
        num_uavs = int(env_values.get("NUM_UAVS", "2"))

    if num_uavs < 1:
        raise ValueError("NUM_UAVS must be >= 1")

    compose_path = docker_dir / "compose" / "docker-compose.multi-sitl.yml"
    gcs_bridge_path = docker_dir / "config" / "zenoh" / "gcs_bridge.json5"
    tmux_path = docker_dir / "config" / "tmuxinator" / "gcs.yml"

    compose_path.write_text(build_compose_text(num_uavs), encoding="utf-8")
    gcs_bridge_path.write_text(build_gcs_bridge_text(num_uavs), encoding="utf-8")
    tmux_path.write_text(build_tmux_text(num_uavs), encoding="utf-8")

    print(f"Generated configs for NUM_UAVS={num_uavs}")
    print(f" - {compose_path}")
    print(f" - {gcs_bridge_path}")
    print(f" - {tmux_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
